### ISSUE TITLE
Implicit Facttype Readings in Objectification

### ISSUE THREAD

**Issue by k-grosser** [ormsolutions/NORMA#6]
Hi,

Shouldn't this be possible from a modelling point of view? So the aotomatic generation of readings should contain some distinction e.g. by numbers ...

<img width="150" alt="objectification2" src="https://user-images.githubusercontent.com/43414739/45762930-c33f7200-bc2f-11e8-9b29-fa042fd12a46.png">

<img width="490" alt="objectification" src="https://user-images.githubusercontent.com/43414739/45762595-03522500-bc2f-11e8-9233-baf28584bf86.png">

**Comment by mcurland** [comment]
The problem is that automatically generating numbers simply hides the problem, which you may not notice until you see 'x1' and 'x2' as your column names in the database. The core issue here is that when you objectify a ring fact type there is simply more work to achieve clean readings. I did as much as possible here to make this easy--if you select the error from the diagram or verbalization browser you will be taken directly to the spot to fix it.

This was simply a side-effect of adding unique fact type reading validation across the model, which NORMA did not always have. [This originally flagged link fact types in implied objectifications as well, but Terry strongly objected.] You either have to validate this error or you don't. Going out of our way to hide a case that is a valid error is IMO not worth the effort, and simply postpones user adjustments in the long run.

**Comment by k-grosser** [comment]
Ok, understood, but thanks for the explanation.
