### ISSUE TITLE
Visualization of an objectified fact type

### ISSUE THREAD

**Issue by SergeValera** [ormsolutions/NORMA#8]
The way NORMA visualizes objectified fact types in some diagrams is too cumbersome and need to be improved.
These diagrams are those where there is no need to show the object types that are hosted by the roles of the related fact types.
In these cases, a simple object type representation would be already much better.
For me, a simple way forward would be to add a property to the object type "DisplayObjectifiedFactType" with the possible value "AsObjectType only" or "IncludingFactType".
Thanks for considering this enhancement and hopefully implement it...
![capture](https://user-images.githubusercontent.com/35797194/46653951-bf0bd200-cba7-11e8-8f22-54e9d4d10667.PNG)

**Comment by mcurland** [comment]
This is already in the tool. Click on the fact type shape (not the name shape above it) and use the DisplayAsObjectType property to switch to an object type shape. You'll see a small fact type glyph at front of the shape indicating the arity of the objectified fact type. Otherwise, it acts as an object type.

See details in June 2011 readme notes.
